### ISSUE TITLE
v20210525: plugin dark mode: optimization required

### ISSUE THREAD

**Issue by W-Geronius** [wellenvogel/avnav-history-plugin#5]
hard to read in dark mode:

<img width="583" alt="CAPT-20220314-233606" src="https://user-images.githubusercontent.com/18160302/158272595-aa30c967-ea38-4be4-9e2c-ee8075377416.png">

**Comment by wellenvogel** [comment]
I agree.
But the plugin UI is not really prepared to handle night mode at all (as for all of the plugin UIs).
Currently they even do not really know about night mode.
Basically the widget itself should be able to handle this.
For me the UIs from the plugins would not really be in the focus for night mode - external apps anyway would not be able to handle this.
I'm not really sure if it would be of great benefit - night mode (from my pov) is really intended for navigation purposes during the night. Configuring plugins I would not really encounter to be necessary in this environment. You always could use a different device (with night mode disabled) to handle such tasks.

**Comment by W-Geronius** [comment]
yes, you are right - it's a request out of test coverage point of view. 
Not very relevant in a realistic scenario ;) I suggest closing this
